### ISSUE TITLE
Linking License to ReadMe file

### ISSUE THREAD

**Issue by krupalitrivedi** [pushkaraj2007/Cardit#13]
It is important to have a License for the repository! It really helps in the long term. I believe that you just have to select the License from the predefined ones!

**Comment by pushkaraj2007** [comment]
I have added MIT license. Or you talking about something else?

**Comment by krupalitrivedi** [comment]
Linking the same in the ReadMe :) Sorry for not mentioning it in detail. It can be a good first issue. Someone can link the license in the ReadMe file.

**Comment by pushkaraj2007** [comment]
Do you mean just like we have added contributors section in the readme file?

**Comment by pushkaraj2007** [comment]
Do you mean just like we have added contributors section in the readme file?

**Comment by krupalitrivedi** [comment]
Yes perfectly like that, I'll also add a screenshot

![image](https://user-images.githubusercontent.com/99717469/187083660-5bbe4721-7653-4eb0-84b1-2d779d6d5b67.png)

**Comment by pushkaraj2007** [comment]
Great, thanks for creating issue. 

If you want you can change the title and description of the issue to understand it more clearly for the beginners.

**Comment by ayushmangarg2003** [comment]
Hey I am a beginner and would like to work on this Issue

**Comment by pushkaraj2007** [comment]
> Hey I am a beginner and would like to work on this Issue

Sure, go ahead.
