### ISSUE TITLE
[BUG] Loading animation not looking proper on small screen devices. 

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Cardit#16]
## Summary:

**Problem**: The loading animation which show up on clicking Create card button is not responsive for small screen devices. 

**Solution**: Try fixing it by adding margin or making the parent flex, according to different screen sizes. 

## Screenshot:
![IMG_20220909_175448.jpg](https://user-images.githubusercontent.com/107422421/189349315-4ae0382f-8d3c-4897-b830-3f8e8a63701e.jpg)

**Comment by AdwitiyaMishra** [comment]
Hi @pushkaraj2007, I would like to work on this issue. Could you assign it to me?

**Comment by pushkaraj2007** [comment]
> Hi @pushkaraj2007, I would like to work on this issue. Could you assign it to me?

Sure, go ahead!

**Comment by AdwitiyaMishra** [comment]
> > Hi @pushkaraj2007, I would like to work on this issue. Could you assign it to me?
> 
> Sure, go ahead!

Thanks a lot @pushkaraj2007, before I proceed  Can you give some guidance on:

1. How do I get started working on this issue and what it's all about? Give some background knowledge.
2. What are the prerequisites I need to know, like technologies in order to fix it?

**Comment by pushkaraj2007** [comment]
> > > Hi @pushkaraj2007, I would like to work on this issue. Could you assign it to me?
> > 
> > Sure, go ahead!
> 
> Thanks a lot @pushkaraj2007, before I proceed  Can you give some guidance on:
> 
> 1. How do I get started working on this issue and what it's all about? Give some background knowledge.
> 2. What are the prerequisites I need to know, like technologies in order to fix it?

1. It's just about fixing the loading animation responsiveness, with any method you like. 

2. HTML, CSS will be enough. 

Do you know how to send PR?

**Comment by pushkaraj2007** [comment]
> > Thanks a lot @pushkaraj2007, before I proceed  Can you give some guidance on:
> > 
> > 1. How do I get started working on this issue and what it's all about? Give some background knowledge.
> > 2. What are the prerequisites I need to know, like technologies in order to fix it?
> 
> 1. It's just about fixing the loading animation responsiveness issue, with any method you like. 
> 2. HTML, CSS will be enough. 
> 
> Do you know how to commit changes and create a pull request?

**Comment by AdwitiyaMishra** [comment]
> > Thanks a lot @pushkaraj2007, before I proceed  Can you give some guidance on:
> > 
> > 1. How do I get started working on this issue and what it's all about? Give some background knowledge.
> > 2. What are the prerequisites I need to know, like technologies in order to fix it?
> 
> 1. It's just about fixing the loading animation responsiveness, with any method you like.
> 2. HTML, CSS will be enough.
> 
> Do you know how to commit changes and create a pull request?

Yes, I have level of understanding.

**Comment by pushkaraj2007** [comment]
> Yes, I have level of understanding.

That's great!

Start working on this, happy coding :)

**Comment by Manish3212** [comment]
Hey! is this tasked assigned to someone yet?if not can i work on this issues ?

**Comment by pushkaraj2007** [comment]
> Hey! is this tasked assigned to someone yet?if not can i work on this issues ? 

No one is working on this currently. 

So I'm assigning you for this issue. 

Happy coding. 🚀

**Comment by mkaletaa** [comment]
So I did something, can you see it? I set the width of the spinner image to 100%. If you want I can try any other method to solve your problem. By the way, in your javascript file you should write querySelectorAll('.class') not querySelector('.class')

**Comment by pushkaraj2007** [comment]
Issue has been resolved in #24
