### ISSUE TITLE
Add A Sample Profile Card in the Readme

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Cardit#19]
You can add a sample GitHub profile card in the Readme.md file, to let viewers know how the card actually looks like!

**Comment by pushkaraj2007** [comment]
Great suggestion!! 👍

Do you want to work on this?

**Comment by Coding-Hashira** [comment]
> Great suggestion!! 👍
> 
> Do you want to work on this? 

Sure!!

**Comment by pushkaraj2007** [comment]
> > Great suggestion!! 👍
> > 
> > Do you want to work on this? 
> 
> Sure!! 

That's great!

I'm assigning you 🚀

**Comment by Coding-Hashira** [comment]
@pushkaraj2007 Made the PR!

**Comment by pushkaraj2007** [comment]
> @pushkaraj2007 Made the PR!

That's great! 

Let me check it out ✨
