### ISSUE TITLE
Add Beautiful Backgrounds For Card

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Cardit#20]
Apart from just a gradient of two colors, you can also allow users to add an image as the background of their profile card.

You can either add some preset images, or allow user to upload his/her own image, or maybe even both!

**Comment by pushkaraj2007** [comment]
That will be a great addition! 👍

BTW, how can we achieve that by just front end JavaScript? Like what libraries can we use for that?

**Comment by Coding-Hashira** [comment]
> That will be a great addition! 👍
> 
> BTW, how can we achieve that by just front end JavaScript? Like what libraries can we use for that?

I think allowing the user to upload his/her own image isn't possible with Vanilla JavaScript, and no backend. But we can add some beautiful preset images. I believe it's possibly even with no backend! 🤔

**Comment by abitsalihu** [comment]
Hey guys, as @Coding-Hashira said, I can try and implement some kind of code where the user can choose between 4 or more preset photos and make that their background of their profile card? Using Vanilla Javascript.

**Comment by pushkaraj2007** [comment]
> Hey guys, as @Coding-Hashira said, I can try and implement some kind of code where the user can choose between 4 or more preset photos and make that their background of their profile card, using only Vanilla Javascript.

So do you want to work on this?

**Comment by abitsalihu** [comment]
Yeah sure assign me please, I'll make it with some random pictures first and then I'll make a discussion with you guys for what photos to use!

**Comment by pushkaraj2007** [comment]
> Yeah sure assign me please, I'll make it with some random pictures first and then I'll make a discussion with you guys for what photos to use!

That's great! I'm assigning you 👍

Happy coding :)

**Comment by pushkaraj2007** [comment]
This issue has been resolved in #26 PR!
