### ISSUE TITLE
Adding a Contributing Guide

### ISSUE THREAD

**Issue by Coding-Hashira** [pushkaraj2007/Cardit#21]
Adding a contributing guide will help beginners who are planning to contribute in this project.

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue and make a **contribute.md**!

**Comment by Coding-Hashira** [comment]
@abitsalihu Go ahead, mate! 🚀

**Comment by pushkaraj2007** [comment]
Go ahead, @abitsalihu 🔥

**Comment by abitsalihu** [comment]
@pushkaraj2007 please close this issue since it has been resolved. :)

**Comment by pushkaraj2007** [comment]
This issue has been resolved in #23 PR!!
