### ISSUE TITLE
[BUG] Website is not responsive.

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Cardit#3]
## ✨ Summary

**Problem**: The website is currently not responsive and looks terrible on small screen devices.

**Solution**: Add media queries of different screen sizes, and adjust styling accordingly.

## 📸 Screenshot

![cardit-responsiveness-issue](https://user-images.githubusercontent.com/107422421/185785408-f153c419-06bc-4d18-9785-a09b5f4311cc.png)

**Comment by ofonime41** [comment]
Hi, I will like to work on this project.

**Comment by pushkaraj2007** [comment]
> Hi, I will like to work on this project.

Sure, go ahead.

**Comment by pushkaraj2007** [comment]
> Hi, I will like to work on this project.

Sure, go ahead.

**Comment by ofonime41** [comment]
Done
