### ISSUE TITLE
[Feature] Create a navbar.

### ISSUE THREAD

**Issue by pushkaraj2007** [pushkaraj2007/Cardit#7]
Create a navbar from which we can redirect the user to the GitHub repository of this project.

GitHub logo will be preferable for the redirection but it's not mandatory, you are free for the creativity.

**Comment by jglowacz** [comment]
Hi Pushkaraj! I'd be more than happy to help, can I take this one? Thanks!

**Comment by pushkaraj2007** [comment]
> Hi Pushkaraj! I'd be more than happy to help, can I take this one? Thanks!

Great, what do you think about #8 PR?

Can you improve that PR or do you want to work on this from scratch?

**Comment by pushkaraj2007** [comment]
> Hi Pushkaraj! I'd be more than happy to help, can I take this one? Thanks!
> 

Sure, go ahead.
