### ISSUE TITLE
[FEAT] Generate a background picker for the banner

### ISSUE THREAD

**Issue by AbbeyIT** [pushkaraj2007/Cardit#9]
I'm thinking of a feature where users can select their own background banner. To start off, you can make a few gradients selection first. On later part, users can maybe select their own plain color background with color picker.

**Comment by pushkaraj2007** [comment]
It will be great, thanks for creating issue. 👍

Do you want to work on this?

**Comment by adetoye-dev** [comment]
Is anyone already working on this? I'd like to contribute to this as well

**Comment by pushkaraj2007** [comment]
> Is anyone already working on this? I'd like to contribute to this as well

Go, ahead!! 

No one is assigned, as far for this. 🚀

**Comment by adetoye-dev** [comment]
Alright, I'll take on this then 👍

**Comment by pushkaraj2007** [comment]
> You can assign it to me 👍

Alright then, have a great contributing experience!!

**Comment by pushkaraj2007** [comment]
This issue has been resolved !!
